CHANGELOG.md, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Fix AudioFocus bug that could cause the player to stop responding to play/pause in some instances.
Fixes issue #1945
This was caused by the player requesting audio focus on each play (un-pause) and that resulted in a small window of Audio focus loss and then gain. The focus loss results in the player being paused while the player was supposed to play at the time. The solution is to keep track of Audio focus and not request new focus if we already have it.
=> Fix AudoFocus pausing video when attempting to play

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
Fix player crashing when it is being cleared.
=> VEX-4556: The app crashes when the premium episode is loaded

README.md, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
- Allow player to be init before source is provided, and later update once a source is provided.
- Adds handling for providing a empty source in order to stop playback and clear out any existing content
=> VEX-5044: Allow exoplayer to preinit with empty source

CHANGELOG.md, README.md, Video.js, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java
- Add support for `onBufferProgress` prop on Android to get buffer data even when the player is paused.
=> VEX-3245: Buffer Progress UI While Paused

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Add support for detecting if format is supported and exclude unsupported resolutions from auto quality selection and video track info in RN.
=> VEX-5545: Some Android codecs don't support specific resolutions

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Add support for L1 to L3 Widevine fallback if playback fails initially.
=> VEX-5798: Implement DRM L1 to L3 fallback

Video.js, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
Add support for content tracks and improve track selection to work even during ads playback.
Do not merge until Exoplayer logging is disabled!
=> VEX-6011: Align AVOD resolutions with available resolutions on Content

README.md, Video.js, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
This PR changes the behavior on old devices that have poor memory management.
Jira: VEX-6030
https://jira.tenkasu.net/browse/VEX-6030
The solution implied customizing the method shouldContinueLoading from RNVLoadControl to use only the available heap, performing tests on an old Nexus 5 it was determined the ideal bytes allocation to half the reported heap, that provided some buffering during ads but smooth playback during the video with no crashes (23:39 of 23:39 at the moment of writing this, video kept playing as expected after 3 ad breaks)
The fix is only targeting Marshmallow as the reduction of buffer is substantial and other versions that work properly should not get affected.
Depending on the test result of VEX-5758, this same fix can be applied to Nougat
Reviews
Major reviewer …
=> VEX-6030: Reduce buffer size based on heap

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
This PR is intended to prevent memory crashes when the free memory runs out
Jira: VEX-6030
https://jira.tenkasu.net/browse/VEX-6030
Velocity PR: https://github.com/crunchyroll/velocity/pull/2043
By forcefully calling the garbage collector the memory crashes, specially on lower resolutions (<720p) are gone on devices with 2GB of ram or less and Android 6, also testing 3GB Android 7 with this patch, so far is working as intended
- Major reviewer (domain expert): @nickfujita 
- Minor reviewer: @jctorresM 
```
1. Target an android 6 device with 2GB of ram or less
2. Execute yarn start-androidmobile-client
3. Make sure to enable "V2" at "config delta override"
4. Play any episode
5. Skip to the middle then near the end
6. Play the next episode
7. Skip to another part of the video
8. Make sure …
```
=> VEX-6030: Further prevent memory crashes

README.md, Video.js, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
This PR adds core actions to enable or disable screenshots
Jira: VEX-6540
https://jira.tenkasu.net/browse/VEX-6540
velocity PR: https://github.com/crunchyroll/velocity/pull/2248
New core actions were added to control the player surface and mark it as secure. Sending the prop to `react-native-video` will recreate the surface of the player changing it to a SurfaceView and enabling security
- Major reviewer (domain expert): @nickfujita
- Minor reviewer: @armadilio3 
Android mobile
```
Pure offline
1. execute yarn start-androidmobile-client
2. log in as mega fan
3. download an episode
4. turn on airplane mode
5. play the downloaded episode
6. try to take a screenshot, confirm the screenshot do not include any content
Online client playing offline content
7. …
```
=> VEX-6540: Disable recording when playing local videos

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
JIRA: [VEX-6778](https://jira.tenkasu.net/browse/VEX-6778) 
Move video track info request logic entirely on a different thread, completely preventing ANRs in this section of code.
=> VEX-6778: Android: React Native video getVideoTrackInfoFromManifest crash

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Move DRM initialization logic into a separate thread to prevent ANRs.
JIRA: VEX-6779
https://jira.tenkasu.net/browse/VEX-6779
=> VEX-6779: React Native Video buildDrmSessionManager crash

README.md, Video.js, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java
This PR adds the new prop `onPlaybackStateChanged`
Velocity PR: https://github.com/crunchyroll/velocity/pull/2401
Jira: VEX-6350
Using the new prop from `react-native-video` we can know the current state of the player, which helps us identify if the player state is out of sync with the player state caused by an external pause (described in the ticket) the code is simple if the player reports it's stopped and velocity's state reports it's playing, sync the states to the value of the player.
- Major reviewer (domain expert): @armadilio3 
- Minor reviewer: @jctorresM 
**Android mobile**
Test harness: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-6350-pause-video-when-externally-paused/android-mobile/android-app-debug.apk
Client app: …
=> VEX-6350: add onPlaybackStateChanged prop

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Move to the new way of detecting seek end and remove `onSeekProcessed` which was deprecated.
JIRA: VEX-6099
=> VEX-6099: Android: Progress knob jumps backward after tapping Skip Forwards multiple times

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
On low end devices when replaying same content too quickly DRM could fail with an uncaptured error (`DrmSessionException`). To prevent this we now check for that error and retry DRM one more time.
=> VEX-6891: Android: Infinite loading when closing & reopening the player on low end devices

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
This PR will fix the crash from the experiment on `react-native-video`
Jira: VEX-7093
velocity PR: https://github.com/crunchyroll/velocity/pull/2443
The crash was caused by using the player object before it was set by another thread, the change simply waits for the player to be available before executing any player interaction after DRM initialization.
- Major reviewer (domain expert): @jctorresM 
- Minor reviewer: @jacob-livingston 
Test harness: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-7093-crash-in-exoplayer/android-mobile/android-app-debug.apk
Client app: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-7093-crash-in-exoplayer/androidmobile-client/etp-android-debug.apk
```
1. Execute yarn start-androidmobile-client --clean
2. Play a video
3. Make sure the video plays …
```
=> VEX-7093: Protect initialization of DRM

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
This PR handles autoplay after disconnection
Jira: VEX-6625
There was an error in react-native-video not being properly handled, in addition, the state of the player when reconnecting using a free user was not the expected one, requesting the player to keep playing when ready, made the behavior consistent in all scenarios
Velocity PR: https://github.com/crunchyroll/velocity/pull/2430
- Major reviewer (domain expert): @jctorresM
- Minor reviewer: @jacob-livingston 
- [/] Documentation has been created and/or updated
Test harness: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-6625-ensure-free-user-enabling-cellular-continues-playing/android-mobile/android-app-debug.apk
Client app: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-6625-ensure-free- …
=> VEX-6625: Handle state to keep playing after gaining connection

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
When moving init logic to a different thread we missed one function that was not captured if an error occurred. This PR wraps the source init function that happens on a different thread in a try/catch to capture any errors that occur.
=> VEX-7094: Android: Crash in ReactExoplayerView.java Line 694

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Prevent crashing when track selector is null.
JIRA: VEX-7095
https://jira.tenkasu.net/browse/VEX-7095
=> VEX-7095: Crash in ReactExoplayerView.java Line 1059

README.md, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Fix RNV-3005 errors when exiting the player and loading a new video immediately. In most cases this error was just happening internally and the user would not experience it, but it skewed the error rate reporting.
=> VEX-6834: Android: Sometimes the player fails with RNV-3005

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Prevent edge case crash where video track info is attempted to load before data source factory is initialised.
=> VEX-7342: Android: Crash in ReactExoplayerView.java Line 1113

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
This PR adds null checks to `trackSelector` that was causing a crash
Jira: VEX-7430
Velocity PR: https://github.com/crunchyroll/velocity/pull/2535
As part of the Velocity rollout, one of the crashes unveiled was on `react-native-video`:`1121`
The crash was caused by the instance `trackSelector` being `null` which happens either at the start of the process or when `releasePlayer()` is invoked, since the only entry point was through an event that only gets registered when we have a valid player, it means this crash happened when the player was being released. Having that in mind, there's no need to retrieve valid video tracks and it's safe to just return an empty `WritableArray`
The crash happened on multiple devices with no specific Android version
- Major reviewer (domain expert): …
=> VEX-7430: Add null checks to trackSelector

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, package.json
This PR fixes the exception found in Crashlytics for 3.24
Jira: VEX-7817
Velocity PR: https://github.com/crunchyroll/velocity/pull/2647
There was a crash on line 1078 where `trackSelector` is null at the time of destroying the player, to contain the exception the video tracks are returned as an empty list if `trackSelector` is null.
- Major reviewer (domain expert): @adrian-hammers 
- Minor reviewer: @jacob-livingston 
- [/] Documentation has been created and/or updated
Test harness: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-7817-exception-on-1078/android-mobile/android-app-debug.apk
Client app: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-7817-exception-on-1078/androidmobile-client/etp-android-debug.apk
```
1. yarn …
```
=> VEX-7817: Prevent exception on getVideoTrackInfo

API.md, android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
This PR ports previous fixes to the latest react-native-video
Jira: VEX-7861
Velocity PR: https://github.com/crunchyroll/velocity/pull/2680
Previous improvements were not merged to the upstream and were lost when we upgraded the version, this PR ports the fixes to the current code.
Specifically, the fixes are, to disable backbuffer when free memory is too low, and restrict the maximum video quality based on the device's capabilities
- Major reviewer (domain expert): @jctorresM 
- Minor reviewer: @rogercrunchyroll 
- [/] Documentation has been created and/or updated
Test harness: https://static.cx-staging.com/vilos-v2-qa/task/VEX-7861-re-enable-backbuffer/android-mobile/android-app-debug.apk
Client app: …
=> VEX-7861: Port previous fixes to current code

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java
This PR adds data to the errors sent to NewRelic
Jira: VEX-7847
Velovity PR: https://github.com/crunchyroll/velocity/pull/2684
Updated error codes: https://wiki.tenkasu.net/pages/resumedraft.action?draftId=917440198&draftShareId=a92db640-f929-47ca-8242-1e2074d85d29&
New Relic error reporting: https://wiki.tenkasu.net/pages/resumedraft.action?draftId=1448882419&draftShareId=4f0388cf-66fa-4549-a90e-58fb63294977&
As previously coordinated, the NewRelic class in the client allows Velocity to send any additional objects in string format, taking advantage of that, we are adding additional information to help us diagnose potential issues with the content delivery or playback services.
- Major reviewer (domain expert): @jctorresM 
- Minor reviewer: @rogercrunchyroll 
- [/] Unit tests have been …
=> VEX-7847: add info to errors

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
This PR fixes crash when destroying player while seek is in progress.
Jira: VEX-7950
Velocity PR: https://github.com/crunchyroll/velocity/pull/2694
When exiting the player we remove all references, but if a seek was in progress it would crash when removing passed segments. To resolve this a null check was added to prevent accessing properties from player if it is null.
Reviews
Major reviewer (domain expert): @gabriel-rivero 
Minor reviewer: @rogercrunchyroll 
Android
1. Execute yarn start-androidmobile-client --clean
2. Play any video
3. Resume any video
4. Pause and quick rewind 10s multiple times
5. Right after rewinding press back
6. Do this multiple times since the repro rate is around 30%
=> VEX-7950: Android: Crash on tablet when exiting the player

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
This PR fixes 2 `react-native-video` crashes that were detected during the rollout
Jira: VEX-8156
Jira: VEX-8157
Velocity PR: https://github.com/crunchyroll/velocity/pull/2781
Both crashes happened because the Android activity was not available and there were unprotected chained calls assuming the activity was present, during testing it was determined the condition happened when the player was being destroyed and the reference was removed already
- Major reviewer (domain expert): @JulioTorresCR 
- Minor reviewer: @jacob-livingston 
- Optional minor reviewer: @armadilio3 
- [/] Documentation has been created and/or updated
Test harness: https://static.cx-staging.com/vilos-v2-qa/bugfix/VEX-8156-fix-rnv-crashes/android-mobile/android-app-debug.apk
Client …
=> VEX-8156: prevent crashes found in initial rollout

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Fixes null pointer exception when video format is null.
=> ETPAND-9766: Fix NullPointerException (ReactExoplayerView.videoLoaded)

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
There was a crash happening internally within Exoplayer when a native source was used and the video ended. This was caused by the player calling init when the video ends which corresponded with the native source change so it caused a crash internally because the source was no longer available.
=> ETPAND-9785: Fix crash when video ends using a native source

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Re-layout when player is ready to make sure that the layout is visible when playback starts.
=> ETPAND-9775: Screen is black but the audio is heard

android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
Add padding to top and bottom of CSAI FrameLayout.
=> ETPAND-9757: There's no space between the "?" and the timeline for the CSAI ads on tablet
